spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: 7316
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace